import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
process.env.BOT_USAGE_LOG = "off";
process.env.GITHUB_ACTIONS = "false";
const { config } = await import("../src/config.js");
const { localSlot, nextSlot, nightKey } = await import("../src/schedule.js");
const { imageApproval, imageApprovalProblem } = await import("../src/image-approval.js");
const { contentHash, contentProblem, copyProblems } = await import("../src/readiness.js");
const { parseXrayVerdict } = await import("../src/verify.js");
const { postImage, reply } = await import("../src/threads.js");
const { PersistenceError } = await import("../src/persistence.js");
const { repairQueueSlots } = await import("../src/queue.js");
const { completeSentence } = await import("../src/captions.js");
assert.equal(localSlot("2026-09-10").toISOString(), "2026-09-10T19:00:00.000Z");
assert.equal(localSlot("2026-12-10").toISOString(), "2026-12-10T20:00:00.000Z");
assert.equal(nightKey(new Date("2026-09-10T23:30:00Z")), "2026-09-10");
assert.equal(nextSlot(localSlot("2026-12-10")).toISOString(), "2026-12-11T20:00:00.000Z");
const cond: any = { diagnosis: "Fixture condition", symptom: "pain", keyFindings: "two coherent structures", view: "PA wrist", requiredObservations: ["two structures"] };
const verdict = parseXrayVerdict(JSON.stringify({ unexplainedFindings: [], singleAnswerSupported: true, diagnosticReason: 'Distinct fixture finding', plausible: true, correctBodyPart: true, depictsDiagnosis: true, severity: "pass", defects: [], observations: [{ expected: "two structures", observed: "two structures", assessable: true, matches: true }] }), cond);
assert.equal(verdict.ok, true);
assert.equal(parseXrayVerdict(JSON.stringify({ ...JSON.parse(verdict.raw), observations: [] }), cond).ok, false);
const png = Buffer.from("test");
const c: any = { folder: "one", source: "generated", diagnosis: cond.diagnosis, symptom: "pain", hook: "a strange shape", condition: cond, generated: { threadsCaption: "A puzzling shape", threadsCaptionAlt: "", threadsAnswer: "Answer: Fixture condition" }, imageApproval: imageApproval(png, cond, verdict) };
assert.equal(imageApprovalProblem(c, png), null);
assert.match(imageApprovalProblem({ ...c, condition: { ...cond, symptom: "changed history" } }, png)!, /vignette changed/);
assert.match(imageApprovalProblem({ ...c, condition: { ...cond, requiredObservations: ["three structures"] } }, png)!, /inputs changed/);
c.contentReview = { sha256: contentHash(c) }; assert.equal(contentProblem(c), null);
c.generated.threadsAnswer += " Changed"; assert.match(contentProblem(c)!, /changed/);
c.generated.threadsCaption = "Fixture condition"; assert.ok(copyProblems(c).some(p => /reveals/.test(p)));
let writes = 0;
globalThis.fetch = async () => { writes++; throw new Error("Must not reach network"); };
await assert.rejects(postImage("url", "caption", { assetIdentity: "new-image:new-inputs", publication: { get: () => ({ creationId: "pending", createdAt: new Date().toISOString(), params: { text: "caption" }, assetIdentity: "old-image:old-inputs" }), set: () => { writes++; } } }), PersistenceError);
await assert.rejects(reply("parent", "corrected answer", undefined, undefined, { get: () => ({ creationId: "pending", createdAt: new Date().toISOString(), params: { text: "old incorrect answer", reply_to_id: "parent" } }), set: () => { writes++; } }), PersistenceError);
assert.equal(writes, 0);
assert.throws(() => completeSentence("An unfinished clinical statement that cannot fit", 12), /rewrite/);
const dir = mkdtempSync(join(tmpdir(), "queue-audit-")); config.casesDir = dir; config.activeTz = "Africa/Cairo"; config.postHourLocal = 22;
const queue: any[] = ["one", "two"].map((folder, i) => ({ folder, diagnosis: `Queue fixture ${i}`, source: "manual", postAt: "2020-01-01T19:00:00Z" }));
for (const c of queue) mkdirSync(join(dir, c.folder));
const state: any = { getStages: () => ({}), publication: () => ({ get: () => undefined }) };
repairQueueSlots(queue, state, new Date("2026-09-10T20:00:00Z"));
assert.equal(queue[0].postAt, "2026-09-10T19:00:00.000Z"); assert.equal(queue[1].postAt, "2026-09-11T19:00:00.000Z");
assert.equal(JSON.parse(readFileSync(join(dir, "two", "case.json"), "utf8")).postAt, queue[1].postAt);
console.log("PASS Cairo DST, nightly backlog slots, image/criteria identity, copy invalidation, pending asset hold and complete clinical sentences");
